<?php
/**
 * Created by PhpStorm.
 * User: Menno
 * Date: 21-12-2018
 * Time: 11:54
 *
 * 0105: Source of comment
 */
namespace mmerlijn\msg\src\Hl7\tables;

class Table0006 extends Table
{
    protected static $name="Religion";
    protected static $table = [
        'AGN' => 'Agnostic'
        , 'ATH' => 'Atheist'
        , 'BAH' => 'Baha\'i'
        , 'BUD' => 'Buddhist'
        , 'BMA' => 'Buddhist: Mahayana'
        , 'BTH' => 'Buddhist: Theravada'
        , 'BTA' => 'Buddhist: Tantrayana'
        , 'BOT' => 'Buddhist: Other'
        , 'CFR' => 'Chinese Folk Religionist'
        , 'CHR' => 'Christian'
        , 'ABC' => 'Christian: American Baptist Church'
        , 'AMT' => 'Christian: African Methodist Episcopal'
        , 'AME' => 'Christian: African Methodist Episcopal Zion'
        , 'ANG' => 'Christian: Anglican'
        , 'AOG' => 'Christian: Assembly of God'
        , 'BAP' => 'Christian: Baptist'
        , 'CAT' => 'Christian: Roman Catholic'
        , 'CRR' => 'Christian: Christian Reformed'
        , 'CHS' => 'Christian: Christian Science'
        , 'CMA' => 'Christian: Christian Missionary Alliance'
        , 'COC' => 'Christian: Church of Christ'
        , 'COG' => 'Christian: Church of God'
        , 'COI' => 'Christian: Church of God in Christ'
        , 'COM' => 'Christian: Community'
        , 'COL' => 'Christian: Congregational'
        , 'EOT' => 'Christian: Eastern Orthodox'
        , 'EVC' => 'Christian: Evangelical Church'
        , 'EPI' => 'Christian: Episcopalian'
        , 'FWB' => 'Christian: Free Will Baptist'
        , 'FRQ' => 'Christian: Friends'
        , 'GRE' => 'Christian: Greek Orthodox'
        , 'JWN' => 'Christian: Jehovah\'s Witness'
        , 'LUT' => 'Christian: Lutheran'
        , 'LMS' => 'Christian: Lutheran Missouri Synod'
        , 'MEN' => 'Christian: Mennonite'
        , 'MET' => 'Christian: Methodist'
        , 'MOM' => 'Christian: Latter-day Saints'
        , 'NAZ' => 'Christian: Church of the Nazarene'
        , 'ORT' => 'Christian: Orthodox'
        , 'COT' => 'Christian: Other'
        , 'PRC' => 'Christian: Other Protestant'
        , 'PEN' => 'Christian: Pentecostal'
        , 'COP' => 'Christian: Other Pentecostal'
        , 'PRE' => 'Christian: Presbyterian'
        , 'PRO' => 'Christian: Protestant'
        , 'QUA' => 'Christian: Friends'
        , 'REC' => 'Christian: Reformed Church'
        , 'REO' => 'Christian: Reorganized Church of Jesus Christ-LDS'
        , 'SAA' => 'Christian: Salvation Army'
        , 'SEV' => 'Christian: Seventh Day Adventist'
        , 'SOU' => 'Christian: Southern Baptist'
        , 'UCC' => 'Christian: United Church of Christ'
        , 'UMD' => 'Christian: United Methodist'
        , 'UNI' => 'Christian: Unitarian'
        , 'UNU' => 'Christian: Unitarian Universalist'
        , 'WES' => 'Christian: Wesleyan'
        , 'WMC' => 'Christian: Wesleyan Methodist'
        , 'CNF' => 'Confucian'
        , 'ERL' => 'Ethnic Religionist'
        , 'HIN' => 'Hindu'
        , 'HVA' => 'Hindu: Vaishnavites'
        , 'HSH' => 'Hindu: Shaivites'
        , 'HOT' => 'Hindu: Other'
        , 'JAI' => 'Jain'
        , 'JEW' => 'Jewish'
        , 'JCO' => 'Jewish: Conservative'
        , 'JOR' => 'Jewish: Orthodox'
        , 'JOT' => 'Jewish: Other'
        , 'JRC' => 'Jewish: Reconstructionist'
        , 'JRF' => 'Jewish: Reform'
        , 'JRN' => 'Jewish: Renewal'
        , 'MOS' => 'Muslim'
        , 'MSU' => 'Muslim: Sunni'
        , 'MSH' => 'Muslim: Shiite'
        , 'MOT' => 'Muslim: Other'
        , 'NAM' => 'Native American'
        , 'NRL' => 'New Religionist'
        , 'NOE' => 'Nonreligious'
        , 'OTH' => 'Other'
        , 'SHN' => 'Shintoist'
        , 'SIK' => 'Sikh'
        , 'SPI' => 'Spiritist'
        , 'VAR' => 'Unknown'
    ];

}