<?php
/**
 * Created by PhpStorm.
 * User: Menno
 * Date: 2-2-2019
 * Time: 15:53
 */

namespace mmerlijn\msg\src\Hl7\tables;


class Table0535 extends Table
{
    protected static $name='Signature Code';
    protected static $table=[
        "C" => "Signed CMS-1500 claim form on file, e.g. authorization for release of any medical or other information necessary to process this claim and assignment of benefits.",
        "S" => "Signed authorization for release of any medical or other information necessary to process this claim on file.",
        "M" => "Signed authorization for assignment of benefits on file.",
        "P" => "Signature generated by provider because the patient was not physically present for services.",
    ];
}